import feladat7
#import feladat8
#import feladat9
#import feladat10
#import feladat11
#import feladat12
#import feladat13
#import feladat14
#import feladat15
#import feladat16
#import feladat17
#import feladat18
#import feladat19
#import feladat20
#import feladat21
